module.exports = {
  ENV: 'test',
  MONGODB_URI: 'mongodb://127.0.0.1:27017/auth_test',
  PORT: process.env.PORT || 5000,
  PUBLIC_URL: 'http://localhost:5000',
  JWT_SECRET: process.env.JWT_SECRET,
  NODE_MAILER_USER: 'baylee.hauck53@ethereal.email',
  NODE_MAILER_PASS: process.env.ETHEREAL_PASS,
  EMAIL_SECRET: process.env.EMAIL_SECRET,
  FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID,
  FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
};
